version: "3"

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: clinica
      POSTGRES_DB: clinica
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/bitnami/postgresql/data
